### ISSUE TITLE
Add Clang-format config file

### ISSUE THREAD

**Issue by BardurArantsson** [philipp-classen/CppQuickCheck#11]
Please add the `clang-format` configuration file to the repository.

Without the config file the process of formatting using `clang-format` is not reproducible. For example, I'm getting a lot of "spurious" changes which I just run `clang-format -i ...` on my system.

The file can be generated by running `clang-format -style=... -dump-config` on your system. (You might need to change the settings to whatever you used originally when reformatting.)

**Comment by philipp-classen** [comment]
I checked in the .clang-format file and reformatted with the current settings.
Hope it is now reproducible.

**Comment by BardurArantsson** [comment]
Thanks, I'll check and report back :).

**Comment by BardurArantsson** [comment]
EDIT: NVM, I'm a dummy. Not sure how it happened, but I may have run *my* copy of .clang-format through clang-format itself...

**Comment by philipp-classen** [comment]
@BardurArantsson I also forgot to CMakeLists.txt that it uses the .clang-format file. It should work now if you run "make clangformat".

**Comment by BardurArantsson** [comment]
Works for me! :+1:
